# -*- coding: utf-8 -*-
"""Organic Farming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cidxKqQC0YCySitlECWvuozh8ysDNI-i
"""

import gradio as gr
import requests
import json

class OrganicFarmChatbot:
    def __init__(self):
        self.api_key = None
        self.conversation_history = []
        self.is_verified = False

    def verify_api_key(self, api_key):
        """Verify the Groq API key"""
        if not api_key or not api_key.strip():
            return "❌ Please enter an API key", False

        try:
            response = requests.post(
                "https://api.groq.com/openai/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json"
                },
                json={
                    "model": "llama-3.3-70b-versatile",
                    "messages": [{"role": "user", "content": "Hello"}],
                    "max_tokens": 10
                }
            )

            if response.status_code == 200:
                self.api_key = api_key
                self.is_verified = True
                self.conversation_history = []
                welcome_msg = "✅ API Key verified successfully!\n\n🌱 Welcome to the Organic Farming Chatbot! I'm here to help you with all your questions about organic farming, sustainable agriculture, composting, pest management, crop rotation, and more. How can I assist you today?"
                return welcome_msg, True
            else:
                return f"❌ Invalid API key. Status code: {response.status_code}", False

        except Exception as e:
            return f"❌ Error verifying API key: {str(e)}", False

    def is_organic_farming_question(self, question):
        """Check if the question is related to organic farming"""
        if not self.is_verified or not self.api_key:
            return False

        try:
            response = requests.post(
                "https://api.groq.com/openai/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "Content-Type": "application/json"
                },
                json={
                    "model": "llama-3.3-70b-versatile",
                    "messages": [
                        {
                            "role": "system",
                            "content": "You are a classifier. Respond with ONLY 'YES' if the question is related to organic farming, sustainable agriculture, composting, natural pest control, crop rotation, soil health, organic certification, permaculture, or any aspect of organic food production. Respond with ONLY 'NO' if it is not related to these topics."
                        },
                        {
                            "role": "user",
                            "content": question
                        }
                    ],
                    "max_tokens": 5,
                    "temperature": 0
                }
            )

            if response.status_code == 200:
                data = response.json()
                answer = data["choices"][0]["message"]["content"].strip().upper()
                return answer == "YES"
            else:
                return False

        except Exception as e:
            print(f"Classification error: {e}")
            return False

    def chat(self, message, history):
        """Main chat function"""
        if not self.is_verified:
            return history + [[message, "⚠️ Please verify your API key first using the 'Verify API Key' button above."]]

        if not message or not message.strip():
            return history

        # Check if question is related to organic farming
        is_relevant = self.is_organic_farming_question(message)

        if not is_relevant:
            response = "🚫 I apologize, but I can only answer questions related to organic farming and sustainable agriculture. Please ask me about topics like:\n\n• Organic pest control\n• Composting techniques\n• Soil management\n• Crop rotation\n• Organic certification\n• Sustainable farming practices\n• Permaculture\n• Natural fertilizers"
            return history + [[message, response]]

        # Prepare messages for API
        messages = [
            {
                "role": "system",
                "content": "You are an expert organic farming consultant. Provide helpful, accurate, and practical advice about organic farming, sustainable agriculture, composting, natural pest management, crop rotation, soil health, and related topics. Be concise but informative."
            }
        ]

        # Add conversation history
        for user_msg, assistant_msg in history:
            messages.append({"role": "user", "content": user_msg})
            messages.append({"role": "assistant", "content": assistant_msg})

        # Add current message
        messages.append({"role": "user", "content": message})

        try:
            response = requests.post(
                "https://api.groq.com/openai/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "Content-Type": "application/json"
                },
                json={
                    "model": "llama-3.3-70b-versatile",
                    "messages": messages,
                    "max_tokens": 1000,
                    "temperature": 0.7
                }
            )

            if response.status_code == 200:
                data = response.json()
                assistant_response = data["choices"][0]["message"]["content"]
                return history + [[message, assistant_response]]
            else:
                error_msg = f"❌ Error: API returned status code {response.status_code}"
                return history + [[message, error_msg]]

        except Exception as e:
            error_msg = f"❌ Sorry, there was an error processing your request: {str(e)}"
            return history + [[message, error_msg]]

# Create chatbot instance
chatbot = OrganicFarmChatbot()

# Create Gradio interface
with gr.Blocks(theme=gr.themes.Soft(), css="""
    .gradio-container {background: linear-gradient(to bottom right, #f0fdf4, #d1fae5);}
    .chat-container {border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);}
""") as demo:

    gr.Markdown("""
    # 🌱 Organic Farming Chatbot
    ### Your Sustainable Agriculture Assistant

    This chatbot provides expert advice on organic farming topics only.
    """)

    with gr.Row():
        with gr.Column(scale=3):
            api_key_input = gr.Textbox(
                label="Groq API Key",
                type="password",
                placeholder="Enter your Groq API key here...",
                info="Get your API key from https://console.groq.com/"
            )
        with gr.Column(scale=1):
            verify_btn = gr.Button("🔐 Verify API Key", variant="primary", size="lg")

    verification_status = gr.Textbox(
        label="Status",
        interactive=False,
        lines=3
    )

    gr.Markdown("---")

    chatbot_interface = gr.Chatbot(
        label="Chat",
        height=400,
        bubble_full_width=False,
        avatar_images=(None, "🌾")
    )

    msg = gr.Textbox(
        label="Your Message",
        placeholder="Ask about organic farming, composting, pest control, etc...",
        lines=2
    )

    with gr.Row():
        submit_btn = gr.Button("📤 Send", variant="primary")
        clear_btn = gr.Button("🗑️ Clear Chat")

    gr.Markdown("""
    ---
    **Topics I can help with:**
    - Organic pest control methods
    - Composting techniques
    - Soil health and management
    - Crop rotation strategies
    - Organic certification process
    - Natural fertilizers
    - Sustainable farming practices
    - Permaculture design
    """)

    # Event handlers
    def verify_key(api_key):
        message, success = chatbot.verify_api_key(api_key)
        return message

    verify_btn.click(
        fn=verify_key,
        inputs=[api_key_input],
        outputs=[verification_status]
    )

    submit_btn.click(
        fn=chatbot.chat,
        inputs=[msg, chatbot_interface],
        outputs=[chatbot_interface]
    ).then(
        lambda: "",
        None,
        msg
    )

    msg.submit(
        fn=chatbot.chat,
        inputs=[msg, chatbot_interface],
        outputs=[chatbot_interface]
    ).then(
        lambda: "",
        None,
        msg
    )

    clear_btn.click(
        fn=lambda: [],
        inputs=None,
        outputs=[chatbot_interface]
    )

if __name__ == "__main__":
    demo.launch(share=False)